apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vq7hctane-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vq7hctane-nodejs 
  name: vq7hctane-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vq7hctane-nodejs 
